#!/usr/bin/env python

# bin
# Jim Bagrow
# Last Modified: 2011-02-27

import sys
import numpy

if __name__ == '__main__':
    
    # eventually make this take a file and num_bins (bin width?)
    try:
        num_bins = int(sys.argv[1])
    except IndexError:
        num_bins = None
    
    data = [ float(x) for x in sys.stdin.readlines() ]
    
    if num_bins is None:
        from math import sqrt
        num_bins = int(sqrt(len(data)))
    
    hist,bin_edges = numpy.histogram(data, bins=num_bins, normed=True)
    bin_centers = bin_edges[0:-1] + 0.5*(bin_edges[1:] - bin_edges[0:-1])
    
    for b,h in zip(bin_centers, hist):
        print b, h


