#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name"
    echo -e ""
    echo -e "Compute the correlation coefficient of the xy-data received from STDIN."
    echo -e "Example:\n  cat xy.txt | $name"
	exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) usage;;
    esac
    shift
done

awk '
{
  sx1 += $1; sx2 += $1*$1;
  sy1 += $2; sy2 += $2*$2;
  sxy += $1*$2;
  N++;
}
 
END {
  xmean = sx1/N;
  ymean = sy1/N;
  xSigma = sx2 - 2*xmean*sx1 + N*xmean*xmean;
  ySigma = sy2 - 2*ymean*sy1 + N*ymean*ymean;
  r = 0;
  if (xSigma*ySigma > 0)
    r = (sxy - xmean*sy1 - ymean*sx1 + N*xmean*ymean)/sqrt(xSigma * ySigma);
  print r;
  if (r > 1 || r < -1){
    printf("SERIOUS ERROR! CORRELATION COEFFICIENT");
    printf(" OUTSIDE RANGE -1..1\n");
  }
} 
'

# The above awk command was adapted from the "grand example" on wikibooks:
#     http://en.wikibooks.org/wiki/AWK
# (originally released under the GFDL by the Harvey Mudd College Department of
#  Computer Science)
