#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name [-n]"
    echo -e ""
    echo -e "Read data from STDIN and count number of occurrences of each unique value."
    echo -e "  Use -n to return the number of occurrences and not the fraction."
    echo -e "Example:\n  cat ages.txt | $name | plot -c \"set xlabel 'age';set ylabel '# people'\""
	exit 1
}

NORMED=true
while getopts "nNh -help" opt; do
  case $opt in
    n | N) NORMED=false;;
        h) usage;;
    -help) usage;;
      [?]) usage;;
  esac
done

if $NORMED; then
    awk ' NF > 0{ counts[$0] = counts[$0] + 1; tot = tot + 1} END { for (word in counts) print word, counts[word]/tot; }' | sort -g
else
    awk ' NF > 0{ counts[$0] = counts[$0] + 1} END { for (word in counts) print word, counts[word]; }' | sort -g
fi

