#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

NORMED=true
while getopts ":nN" opt; do
  case $opt in
    n | N) NORMED=false;;
    \?)    echo "Invalid option: -$OPTARG" >&2;;
  esac
done

if $NORMED; then
    awk ' NF > 0{ counts[$0] = counts[$0] + 1; tot = tot + 1} END { for (word in counts) print word, counts[word]/tot; }' | sort -g
else
    awk ' NF > 0{ counts[$0] = counts[$0] + 1} END { for (word in counts) print word, counts[word]; }' | sort -g
fi
