#!/usr/bin/env python

# el2dd
# Jim Bagrow
# Last Modified: 2011-04-07

import sys, os

name = os.path.basename(sys.argv[0])
usage = \
"""Usage: %s
        
Compute the degree distribution for the network whose edgelist was received
  from STDIN.  Edgelist delimiter must be tab or space. An example edgelist is
  provided: <DATATOOLS>/tutorial/karate.edgelist.  Only unweighted, undirected
  networks are currently supported.

Example:
  cat edgelist.txt | %s | plot -c "set xlabel 'k'; set ylabel 'N(k)'" """ % (name,name)

error = "%s takes no arguments, run `%s --help` for info." % (name,name)

def get_edge(line):
    """first try to split with tab, then with space, no other delimiters are
    currently supported...
    """
    L = line.strip().split("\t")[:2]
    if len(L) == 2:
        return L
    return line.strip().split(" ")[:2]


if __name__ == '__main__':
    if '-h' in sys.argv or '--help' in sys.argv:
        sys.exit(usage)
    elif len(sys.argv) > 1:
        sys.exit(error)
    
    edges = [ get_edge(line) for line in sys.stdin.readlines() ]
    
    n2k = {}
    for ni,nj in edges:
        try:
            n2k[ni] += 1
        except KeyError:
            n2k[ni]  = 1
        try:
            n2k[nj] += 1
        except KeyError:
            n2k[nj]  = 1
    
    k2nk = {}
    for k in n2k.values():
        try:
            k2nk[k] += 1
        except KeyError:
            k2nk[k]  = 1
    
    for k,nk in sorted(k2nk.items()):
        print k, nk

    

