#!/usr/bin/env python

# el2dd
# Jim Bagrow
# Last Modified: 2011-03-12

import sys, os

def get_edge(line):
    """first try to split with tab, then with space, no other delimiters are
    currently supporting...
    """
    L = line.strip().split("\t")[:2]
    if len(L) == 2:
        return L
    return line.strip().split(" ")[:2]


if __name__ == '__main__':
    
    edges = [ get_edge(line) for line in sys.stdin.readlines() ]
    
    n2k = {}
    for ni,nj in edges:
        try:
            n2k[ni] += 1
        except KeyError:
            n2k[ni]  = 1
        try:
            n2k[nj] += 1
        except KeyError:
            n2k[nj]  = 1
    
    k2nk = {}
    for k in n2k.values():
        try:
            k2nk[k] += 1
        except KeyError:
            k2nk[k]  = 1
    
    for k,nk in sorted(k2nk.items()):
        print k, nk

    

