#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

NAME=`basename $0`
BIN="bin"
PLT="plot"
if [[ $NAME == "loghist" ]]; then
    BIN="logbin"
    PLT="plot --log"
fi

usage(){
    echo -e "Usage: $NAME [number of bins]"
    echo -e ""
    echo -e "A shortcut for \`$BIN | $PLT\`.\n"
    echo -e "Example:\n  cat x.dat | $NAME"
    echo -e "is equivalent to:\n  cat x.dat | $BIN | $PLT"
	exit 1
}

while getopts "h -help" flag
do
    case "$flag"  in
        h) usage;;
    -help) usage;;
      [?]) usage;;
    esac
done

# this is the whole thing:
$BIN $1 | $PLT
