#!/usr/bin/env python

# logbin
# Jim Bagrow
# Last Modified: 2011-03-27

"""
    This file is part of Datatools.
    
    Datatools is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    Datatools is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with Datatools.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys, os
import warnings
import numpy

name = os.path.basename(sys.argv[0])
usage = \
"""Usage: %s [number of bins]
        
Compute the histogram of the data received from STDIN using logarithmically sized
  bins.  If the number of bins is unspecified, an estimate is used based on the
  number of data points.
Example:
  cat vals.txt | %s 200 | logplot -c "set xlabel 'x'; set ylabel 'Pr(x)';" """ % (name,name)

error = "Number of bins must be an integer, run `%s --help` for info." % name

if __name__ == '__main__':
    
    if "-h" in sys.argv or "--help" in sys.argv:
        sys.exit(usage)
    try:
        num_bins = int(sys.argv[1])
    except IndexError:
        num_bins = None
    except ValueError:
        sys.exit(error)
    
    data = [ float(x) for x in sys.stdin.readlines() if float(x) > 0 ]
    
    if num_bins is None:
        from math import sqrt
        num_bins = int(sqrt(len(data)))
    
    min_data,max_data = min(data),max(data)
    bin_edges = numpy.logspace( numpy.log10(min_data), numpy.log10(max_data), num_bins )
    
    warnings.simplefilter("ignore", Warning)
    try: # deal with deprecated numpy behavior :(
        hist,bin_edges = numpy.histogram(data, bins=bin_edges, normed=True, density=True)
    except TypeError:
        hist,bin_edges = numpy.histogram(data, bins=bin_edges, normed=True)
    
    bin_centers = bin_edges[0:-1] + 0.5*(bin_edges[1:] - bin_edges[0:-1])
    #print numpy.sum(hist*numpy.diff(bin_edges)) # check normalization...
    
    for b,h in zip(bin_centers, hist):
        print b, h


