#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name [base]"
    echo -e ""
    echo -e "Compute the log-transform of XY-data received from STDIN."
    echo -e "Equivalent to: cat XY.dat | awk '{print log(\$1), log(\$2)}'"
    echo -e "except for the base and that negative data are ignored."
    echo -e ""
    echo -e "  base - the base of the logarithm.  Default is base-ten"
    echo -e ""
    echo -e "Example:\n  cat XY.txt | $name"
	exit 1
}

BASE=10.0
if [ "$1" != "" ]; then
    BASE=$1
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) usage;;
    esac
    shift
done

awk "\$1>0.0&&\$2>0.0 {print log(\$1)/log($BASE), log(\$2)/log($BASE)}"

