#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name "
    echo -e ""
    echo -e "Compute the maximum of the X-data received from STDIN.\n"
    echo -e "Options:"
    echo -e "  -r | --rows : Compute the maximum row-wise (for multi-column data)."
    echo -e "                Returns the maximum of all values on each row."
    echo -e "                Especially handy for \"ragged\" data."
    echo -e ""
    echo -e "Example:\n  cat ages.txt | $name"
	exit 1
}

ROWWISE=false
while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) usage;;
        -r | --rows ) ROWWISE=true;;
esac
    shift
done

# this is the whole command:
if $ROWWISE ; then
    awk '{ max=$1; for (i=1; i<=NF; i++){if ($i > max) max=$i}; print max; }'
else
    awk '{ if(max=="")max=$1; if($1>max) {max=$1}; } END {print max}'
fi

