#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage="Display the smallest value of the numbers read from STDIN\n
\tExample: $ cat data.txt | `basename $0`"
while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) echo -e $usage
                      exit
                      ;;
    esac
    shift
done

awk '{if(min==""){min=$1}; if($1<min) {min=$1}; } END {print min}'
