#!/usr/bin/env python

# num_bins
# Jim Bagrow
# Last Modified: 2011-06-16

"""
    This file is part of Datatools.
    
    Datatools is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    Datatools is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with Datatools.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys, os
from math import sqrt

name = os.path.basename(sys.argv[0])
usage = \
"""Usage: %s

Print the "recommended" number of bins for data received from STDIN: 
  number of bins = floor(sqrt(number of datapoints))

Example:
  cat vals.txt | %s""" % (name,name)

if __name__ == '__main__':
    
    if "-h" in sys.argv or "--help" in sys.argv:
        sys.exit(usage)
    
    N = sum( 1 for x in sys.stdin if x.strip() )
    sys.stdout.write(str( int(sqrt(N)) ))
    sys.stdout.write("\n")
