#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name"
    echo -e ""
    echo -e "Compute the coefficient of determination (or R^2) of the xy-data received"
    echo -e "from STDIN.\n"
    echo -e "Example:\n  cat xy.txt | $name"
	exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) usage;;
    esac
    shift
done

corrcoef | awk '{print $1**2}'

# The above awk command was adapted from the "grand example" on wikibooks:
#     http://en.wikibooks.org/wiki/AWK
# (originally released under the GFDL by the Harvey Mudd College Department of
# Computer Science)

