#!/usr/bin/env python

# scale01
# Jim Bagrow
# Last Modified: 2012-04-17

import sys, os
import math

name = os.path.basename(sys.argv[0])
usage = \
"""Usage: %s

Linearly rescale X-data from STDIN in so that it falls in [0,1]. That is,
  x_scaled = (x-min(x))/(max(x)-min(x)).

Example:
  cat tutorial/x.dat | %s""" % (name,name)


if __name__ == '__main__':
    
    if '-h' in sys.argv[1:] or '--help' in sys.argv[1:]:
        sys.exit( usage )
    
    data = [ float(x) for x in sys.stdin if x.strip() ]
    
    min_x,max_x = min(data), max(data)
    for x in data:
        x01 = (x-min_x) / (max_x - min_x)
        sys.stdout.write("%f\n" % x01 )
        sys.stdout.flush()

