#!/usr/bin/env python

# stepize.py
# Jim Bagrow
# Last Modified: 2011-06-15

import sys, os

name = os.path.basename(sys.argv[0])
usage = \
"""Usage: %s

Removes "vertically duplicate" first-column data received from STDIN.  In other
  words, it only prints lines of STDIN where the first field (X-value) differs
  from that of either the previous line or the subsequent line.  This is useful
  after computing the (c)ccdf since it removes the duplicated points that stack
  up vertically at each unique X_value.

Example:
  cat vals.txt | ccdf | %s | plot """ % (name,name)

error = "Number of bins must be an integer, run `%s --help` for info." % name

if __name__ == '__main__':
    if "-h" in sys.argv or "--help" in sys.argv:
        sys.exit(usage)
    
    p_x, pp_x = None, None
    p_l, pp_l = None, None
    for line in sys.stdin:
        line = line.strip()
        x = line.split()[0]
        if   pp_x == pp_x == None:
            print line
        elif pp_x != p_x or p_x != x:
            print p_l
        
        pp_x = p_x
        pp_l = p_l
        p_x  = x
        p_l  = line
    
    print p_l
        





