#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name [options]"
    echo -e ""
    echo -e "Compute the sum of X-data received from STDIN."
    echo -e ""
    echo -e "Options:"
    echo -e "  -r | --rows : Compute the sum row-wise (for multi-column data)."
    echo -e "                Returns the sum of all values on each row."
    echo -e "                Especially handy for \"ragged\" data."
    echo -e ""
    echo -e "Example:\n  cat ages.txt | $name"
	exit 1
}

ROWWISE=false
while [ "$1" != "" ]; do
    case $1 in
        -h | --help ) usage;;
        -r | --rows ) ROWWISE=true;;
    esac
    shift
done

# this is the whole command:
if $ROWWISE ; then
    awk '{sum=0; for(i=1; i<=NF; i++){sum+=$i}; print sum}'
else
    awk '{sum+=$1} END {print sum}'
fi



