#!/bin/bash

#  This file is part of Datatools.
#  
#  Datatools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Datatools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.

usage(){
    name=`basename $0`
    echo -e "Usage: $name"
    echo -e ""
    echo -e "Print a number of basic summary statistics about data read from STDIN.\n"
    echo -e "Example:\n  cat distribution.txt | $name"
	exit 1
}

NORMED=true
while getopts "h -help" opt; do
  case $opt in
        h) usage;;
    -help) usage;;
      [?]) usage;;
  esac
done


awk 'min == "" {min=max=$1}
$1 < min  {min = $1}
$1 > max  {max = $1}
            {sum+=$1; sumsq+=$1*$1}
END {
    print "    LEN:", NR;
    printf "    MIN: %0.8g\n", min;
    printf "    MAX: %0.8g\n", max;
    print "    AVG:", sum/NR;
    print "    STD:", sqrt(sumsq/NR-(sum/NR)**2);
    print "    SUM:", sum;
}'

